apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - port: 7000
    name: transport
  - port: 7199
    name: jmx
  - port: 9042
    name: cql
  clusterIP: None
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  selector:
    matchLabels:
      app: cassandra 
  serviceName: "cassandra"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: cassandra 
    spec:
      containers:
      - name: nginx
        image: bitnami/cassandra:latest
        env:
        - name: CASSANDRA_TRANSPORT_PORT_NUMBER
          value: "7000"
        - name: CASSANDRA_JMX_PORT_NUMBER
          value: "7199"
        - name: CASSANDRA_CQL_PORT_NUMBER
          value: "9042"
        - name: CASSANDRA_CLUSTER_NAME
          value: "test-cassandra-cluster"
        - name: CASSANDRA_SEEDS
          value: "cassandra-0"
        - name: CASSANDRA_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 7000
          name: transport
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
